clear all
%%
Trial_num = 1;
tau_V = 10;
R = 1; %Mohm
EL = -70;
V_th = -40;
dt = 0.1; % msec
t_stop = 5e3; % msec
tt = 0:dt:t_stop;
p.dt = dt; p.tStop = t_stop;
p = NeuronType(dt, t_stop*1e-3, 'Integ'); % dt in msec, and stop time in sec
tw = 100; % msec as the kernel window
V = zeros(length(tt),Trial_num);
[Inp_slow,inp_sig] = OUprocess(50, p);
Iinj = 10 + 5*Inp_slow; Iinj(Iinj<0) = 0;
figure; plot(tt,Iinj)
xlabel('Time(msec)')
ylabel('Current (pA)')
title('Injected Current generated by OU-Process')
%%
F_binary = zeros(length(tt),Trial_num);
a2 = 4; % pA as the std of noise
for k=1:Trial_num
    eta = OUprocess(5, p);
    I_total = Iinj + a2*eta;
    yy = singleCompartment_ML(I_total*1e-3, p);
    V(:,k) = yy(:,1); 
    F_binary(:,k) = spike_binary(V(:,k));
    fr_ave(k) = sum(F_binary(:,k))/(t_stop/1e3);
end
%figure; plot(fr_ave(1:Trial_num))
figure; plot(tt,V(:,1))
xlabel('Time(msec)')
ylabel('Voltage (mV)')
title('Membrane Potential')
